--DROP TABLE PRODUCT;
--DROP SEQUENCE SEQ_PRODUCT;

CREATE TABLE PRODUCT
(
    ID          INT,
    CODE        VARCHAR2(20),
    NAME        NVARCHAR2(50),
    
    CONSTRAINT PK_PRODUCT PRIMARY KEY (ID),
    CONSTRAINT UN_PRODUCT UNIQUE (CODE)
);

INSERT INTO PRODUCT (ID,CODE,NAME) VALUES (1,'MS-NB-001',N'Microsoft Surface Go');
INSERT INTO PRODUCT (ID,CODE,NAME) VALUES (2,'MS-NB-002',N'Microsoft Surface Pro 7');
INSERT INTO PRODUCT (ID,CODE,NAME) VALUES (3,'AP-PH-001',N'Apple iPhone X');
INSERT INTO PRODUCT (ID,CODE,NAME) VALUES (4,'AP-MB-001',N'Apple Macbook Pro');

CREATE SEQUENCE SEQ_PRODUCT
    START WITH 5
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

--SELECT * FROM PRODUCT;